language: python
sudo: true
python:
  - "3.5"
env:
  - WITH_OPT_DEPS=true
install:
  - if [ "$WITH_OPT_DEPS" = "true" ] ; then pip install -vr requirements.txt; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" =~ ^3\.[4-9] ]] ; then pip install -v git+https://github.com/ProgVal/irctest.git; fi
  - echo "y" | pip uninstall limnoria || true
# command to run tests, e.g. python setup.py test
script:
  - echo $TRAVIS_PYTHON_VERSION
  - python setup.py install
  - if [[ "$TRAVIS_PYTHON_VERSION" =~ ^3\.[4-9] ]] ; then python -m irctest irctest.controllers.limnoria; fi
notifications:
    email: true
