language: python
sudo: false
python:
  - "pypy3"
env:
  - TRY=1
  - TRY=2
  - TRY=3
  - TRY=4
install:
    - pip install -vr requirements.txt
# command to run tests, e.g. python setup.py test
script:
  - echo $TRAVIS_PYTHON_VERSION
  - python setup.py install > /dev/null
  - supybot-test -v --no-network --disable-multiprocessing plugins/Aka
  - cat test-logs/messages.log
notifications:
    email: false
matrix:
  fast_finish: true
